# Generated by Django 5.0.3 on 2024-03-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_active_category_create_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='update_date',
        ),
        migrations.AddField(
            model_name='category',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
